server:
  port: 8080

spring:
  devtools:
    livereload:
      enabled: true # auto reload

  thymeleaf:
    enabled: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8
    username: test
    password: test1234

  jpa:
    database: mysql
    # mysql 설정
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # mariadb 설정
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    properties:
      open-in-view: false
      generate-ddl: true
      show-sql: true
